### ISSUE TITLE
Stream could not be attached for user 

### ISSUE THREAD

**Issue by LifeNT** [Half-Shot/matrix-appservice-twitter#79] opened 2017-01-22 15:44 UTC
2017-01-22 15:42:08.377 error Stream could not be attached for user %s: %s @today_freedom:matrix.org User has no attached timeline room. This is probably a bug.                                   Unhandled rejection TypeError: Cannot read property 'formatting' of undefined                                                         at _storage.get_profile_by_id.then (/root/matrix-appservice-twitter/src/twitter/Twitter.js:218:24)

**Comment by Half-Shot** [comment] 2017-01-22 15:47
Last minute bug caused by a change that will be fixed in #77. Just awaiting review of the PR and then this should be fixed.

**Comment by Half-Shot** [comment] 2017-03-22 13:13
This was presumed fixed so I'll close this.

**Closed as completed by Half-Shot** 2017-03-22 13:13 UTC
Labels: bug, Testing Required
